### ISSUE TITLE
lang-ref: appearance of ->

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#116]
much of the document renders -> as the single-arrow unicode character, where as in real Frege code one writes this as the two-character minus-greaterThan. (from the wording in the lang-ref I would even assume that the unicode version is not allowed in Frege code)

**Comment by Ingo60** [comment]
Yeah, that's how latex does it. It turns out that when one reads papers with typesetted haskell code, it looks like the authors took every effort to make it look more "mathematical".

Can you point to the passage where the wording suggests that the unicode symbol may not be used (which was true untile recently?). I could then insert a table or something where the supported Unixode characters are clearly listed and defined.

**Comment by Dierk** [comment]
One could put that under 2.1 notational conventions, or 2.5 "specialsym" but it would still be confusing like e.g. in 3.1.1 when literal examples contain characters that are not allowed in real code. 
If that could be somehow escaped, then we could do a search-replace. 

Cheers
Dierk

sent from:mobile

**Comment by Ingo60** [comment]
I am in the process of rewriting the reference. I use a new code environment (minted), and this should typeset the code more verbatim. In addition I added a table of unicode shoprtcuts in section 2.1.
