### ISSUE TITLE
Arbitrary instance for HashMap?

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#145]
Should we make the new HashMap an instance of the Arbitrary typeclass such that we can use it easier in QuickCheck?

**Comment by Ingo60** [comment]
There is one in `tests.qc.HM` , however, I am not sure if HashMap is a type that is supposed to appear in other types, so that this would be needed.

And even if it would be needed, you just write

    HM.fromList <$> arbitrary

and that is that.

Generally, I am in the ongoing process to remove "superfluous"  Arbitrary instances and tests from the standard library to avoid bloating the JAR with code that is probably never used.

This is why I have made the `tests/qc` directory. This is built just for the tests, and then thrown away.

**Comment by Dierk** [comment]
fair enough!
