### ISSUE TITLE
Missing links to chat group and mailing list

### ISSUE THREAD

**Issue by xoltar** [Frege/frege#162]
https://github.com/Frege/frege/wiki/Getting-Started says at the end that new users should use the chat group or the mailing list, whose links can be found on the "main page." However, the main page (wiki Home, I interpreted that to mean) does not contain those links.

1. Those links should be on the home page
2. The links should also be on the getting started page directly
3. The getting started page should link directly to which ever page it is we want them to go to, so the user doesn't have to guess. 

I would add them myself but I don't know the right URLs.

**Comment by Dierk** [comment]
Hi xoltar,

the links are a bit down the page, in the "links" section
https://github.com/Frege/frege#links
Forum and else just above under "contact".

I agree that is not very prominent and direct links would be better anyway. Since you offered help: now that you have the links, please feel free to put them in the wiki right at the place where they would have helped you.

Thanks for posting!

**Comment by xoltar** [comment]
Done, thanks!

**Comment by Dierk** [comment]
cool!
