### ISSUE TITLE
a FregeFX repository under the Frege github account

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#166]
So far, I have developed the FregeFX functionality as part of the the Dierk/frepl-gui project. I feel it has now proven useful enough that it deserves its own repo that people can depend on. 
Could we open one under the Frege account? 
I'm not an "owner" so I cannot do this myself.

A second and unrelated questions is whether the FregeFX-REPL should also go there.

**Comment by Ingo60** [comment]
Then I would suggest making you an owner first. (But can't do that right now on phone. Will do it later that evening.)

Second I heartily welcome this.

And third, I think it should be separated. 

I also would love it if it were possible to have another hierarchy level, so that we could have, for example a pace for builders, repls and non - standard libs.

Don't know if that works.

**Comment by Ingo60** [comment]
You are now a member of group Owners.
You should be able to do everything now.

**Comment by Dierk** [comment]
thanks!
