### ISSUE TITLE
diverge of mapP

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#169]
doSomething x = x * x
    mapP (\x -> doSomething x) [9,2,3] 

works, but

    mapP doSomething [9,2,3]

diverges

**Comment by Ingo60** [comment]
Tried this in the command line repl. Works fine for me.

**Comment by Ingo60** [comment]
It seems to have to do with the fact that the computations involving mapP are done outside main.
That is, they're done before the main() function even starts running.

Evidence of this is that when I move the computations inside main, it works.
This is, of course, not acceptable and needs more investigation.

I am using the following test program:

    --- This is an undocumented module
    module tests.comp.Issue169 where

    import frege.lib.ForkJoin(mapP)

    doSomething x = x * x
    -- sumSquares = sum ( mapP doSomething [9, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 4, 10] )
    -- count = length ( mapP doSomething [9, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 4, 10] )
    main args  = do
        let
            sumSquares = sum ( mapP doSomething [9, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 4, 10] )
            count = length ( mapP doSomething [9, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 49, 10, 3, 4, 7, 3, 4, 10] )
        println (sumSquares)
        println (count)

**Comment by Ingo60** [comment]
This case is very mytifiyiing. Looks like I reached the limits of my ability to debug things.

I reduced the code to the absolute minimum (see tests/comp/Issue169.fr). When running it, it deadlocks.
A jstack dump of the situation can be seen here: https://gist.github.com/Ingo60/8173099dbc6e67655c22

From this I can tell that the main thread tries to evaluate the sum of the squares, before even the `main` method has been invoked.  `sum` uses `fold` to go through the provided list and add each element of the list provided. The list, produced by `mapP`, should consist of thunks that are evaluating in or are already evaluated by the worker threads of the fork/jjoin pool. Insofar it is ok that the main thread waits for some thunk to get evaluated.

Incidentally, this is the same thunk the fork/join pool worker thread 1 actually is evaluating. 
But now the mystery begins: what is that thread waiting for? I copy here the relevant part from the aforementioned gist:

     "ForkJoinPool-1-worker-1" daemon prio=10 tid=0x00007fb5c4114000 nid=0x2523 in Object.wait() [0x00007fb5b2697000]
     java.lang.Thread.State: RUNNABLE
	at tests.comp.Issue169$Ĳ$doSomethingƒ6ed52ba2.eval(Issue169.java:148)
	at tests.comp.Issue169$Ĳ$doSomethingƒ6ed52ba2.eval(Issue169.java:143)
	at frege.runtime.Fun1$1.eval(Fun1.java:63)
	at frege.runtime.Delayed.call(Delayed.java:198)
	- locked <0x00000000e1a34290> (a frege.runtime.Fun1$1)
	at frege.runtime.Delayed.forced(Delayed.java:257)  

Here, the thunk for

    doSomething x  -- where x is some number from the list mapped over by mapP

is getting forced, which is another way to say that this is the piece of work the worker thread has to do.
Since the thunk is not yet evaluated, the `Delayed.call` method synchronizes on the thread to force other threads to wait until it is done, and evaluated the function call. So far so good.
But why is the function `doSomething` never actually called, and instead it gets stuck on line 148, which reads:

    148       return (java.lang.Integer)Issue169.doSomething(
    149                 frege.runtime.Delayed.<java.lang.Integer>forced(arg$1)
    150               );

We know that the argument is just a number from the list, so no blocking to expect here. `jstack` tells us that the thread is in Object.wait(), but what object is this? Wy doesn't it go ahead and actually calls the static method?

I have no idea why this is.

Interestingly, we can make the program work in the following ways:

1. Uncommenting the following line before the definition of `sumSquares`:

    sumOther = sum (map doSomething [1,2,3])

2. Replacing `doSomething` in the definition of `sumSquares` with

    (\x -> x * x)

3. Inserting the following line before the definition of `sumSquares` (or `sumNumbers`, as it is called in the actual Issue169 code) in the compiled java code:

     static int foo = (int) frege.runtime.Delayed.<java.lang.Integer>forced(
                                            Ĳ.doSomethingƒ6ed52ba2.inst.apply(42).result());

However, it doesnt help to just call `doSomething` directly. 
It is as if  `doSomething` must be called through its "function pointer" at least once in the main thread, before it can be used from another thread.

**Comment by jburse** [comment]
static { } code is called via the <clinit> method when the class is first used, which is in any case before the main() is called of the class.

**Comment by Ingo60** [comment]
Meanwhile, I read a bit in the JVM spec (chapter 5) and found out that the JVM does indeed lock when a class gets initialized. 

Because `numSquares` is computed during initialization, we can assume that there is this initialization-lock in place. This would explain why the worker threads are waiting to get that lock, given that they need the static method doSomething from that class. 

But I still can't understand why the remedies mentioned above change that game when they still use doSomething.

**Comment by Ingo60** [comment]
Top level definitions are now sufficiently lazy so that this doesn't happen anymore.
