### ISSUE TITLE
Feature request: REPL interpreter like GHCi

### ISSUE THREAD

**Issue by mcandre** [Frege/frege#172]
Interpreters are tremendously help in testing and prototyping code. Could Frege get a `frege` program that behaves like `ghci`, the GHC Haskell Interpreter?

I'm using Frege from Homebrew, which currently offers only the `fregec` compiler.

**Comment by Ingo60** [comment]
We do have a REPL. In fact, we have 3 of them. 
1. The online Repl. 
2. The command line Repl, see sub project frege -repl
3. Dierks FX repl. 

If "homebrew" (whatever that is) doesn't offer them,  I suggest contacting the person or persons who published Frege there. 
I can only say so much: I don't know who this is, nor have we being asked or informed. Which is ok, since Frege is freely redistributable. But the "official" project team cannot be responsible for their shortcomings.

**Comment by ForNeVeR** [comment]
I am not a Mac user at all, but I could add that Homebrew is relatively popular package manager for Mac, and that you definitely could contact Frege package maintainers and ask them to add frege-repl and any other stuff, or even maybe create and maintain these packages yourself if you are willing to participate.

**Comment by Dierk** [comment]
nice. I knew about homebrew but I had no idea that it has a frege distro:
http://brewformulas.org/Frege

**Comment by Ingo60** [comment]
Am 15.09.2015 19:56 schrieb "Dierk König" <notifications@github.com>:
>
> nice. I knew about homebrew but I had no idea that it has a frege distro:
> http://brewformulas.org/Frege

I'm afraid a very old one? 3.17.something.

**Comment by Dierk** [comment]
3.22.524-gcc99d7e
