### ISSUE TITLE
Make doc tool give error information

### ISSUE THREAD

**Issue by mperry** [Frege/frege#174]
The Frege Doc tool does not provide use diagnostic information if it can't create documentation.  This is typical:
```
documenting com.github.mperry.frege.External
there were errors
```

I read https://github.com/Frege/frege/wiki/How-To-Document-Frege-Source and put this in my local file, but get the same error as above.

We need useful error information from the tool.

To reproduce this issue, clone the github repo https://github.com/mperry/frege-gradle-example and run `gradlew fregeDoc`.  The `frege-java:fregeDoc` task will fail.

**Comment by Ingo60** [comment]
I will do some changes to print more information.

However, in the example case, you would then get something like

    com.github.mperry.frege.Bridge is not a frege module.

Therefore, we need a way to confine the doc tasks to frege modules only, or simply ignore java classes that are not frege modules in the doc tool.

**Comment by mperry** [comment]
Part of the help information for the frege doc says:

```  
  * Modules can be specified in three ways:
     *  my.nice.Modul   by name, the Java class for this module must be on the class path
     *  directory/      all modules that could be loaded if the given directory was on the class path, except exxcluded ones
     *  path.jar        all modules in the specified JAR file, except excluded ones
     *
```
Are you implying that a plain Java class in the directory means the tool will fail?  If so, this is something we need to address.

**Comment by Ingo60** [comment]
Indeed, I've come to the same conclusion. It should simply ignore plain
Java classes that are not given explicitly.

Will do that next days.

**Comment by mperry** [comment]
This seems like a good candidate for someone else to get started on the Frege code.  Can you point me in the right direction?

**Comment by Ingo60** [comment]
Well, there are two objectives.

First, actually print the collected error messages instead of just checking
if there have been some.
This is after line 117 of frege/tools/Doc.fr, which collects the results of
documenting the things given in the command line in a list of lists of
Global.

You can find inspiration of how to print the messages in a Global on
frege.compiler.Main there is a function printErrors, or you just use that
function right away.

If you use the eclipse plug in, you need to set the prefix option in the
Frege preferences. Otherwise, the plug in will probably confuse itself and
the code you're compiling. The option should be set to a value like

    project:xx

Where project is the name of the eclipse project you are doing this in.

The other objective is to suppress the message about a class not being a
frege module. For this, we need to dive a bit deeper into the compiler
code. Thus I propose to discuss this later.
