### ISSUE TITLE
Strictness issue

### ISSUE THREAD

**Issue by danielkroeni** [Frege/frege#181]
The following module executes just fine when compiled with ghc but fails with frege:

```haskell
module Main where 

unused =  "Hi" ++ const x "!"
  where x = undefined

main = putStrLn "Should work"
```

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: frege.runtime.Undefined: undefined
	at frege.prelude.PreludeBase.error(PreludeBase.java:17958)
	at frege.prelude.PreludeBase$Ĳ$errorƒ5f3605e2.eval(PreludeBase.java:19913)
	at frege.runtime.Fun1$1.eval(Fun1.java:63)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at Main.<clinit>(Main.java:93)
```

**Comment by Ingo60** [comment]
Yes, Frege is here stricter than Haskell for pragmatic reasons.

The point is that creating a thunk for constants is most often more expensive than to evaluate them right away. In addition, accessing a value through a thunk will cost another indirection each time even when the thunk is evaluated. And for  values of primitive type (like numbers), the access will cost an extra unboxing, since primitive values can only exist in boxed form in thunks.

So the code generation will decide for generating code that evaluates the value to WHNF if the defining expression is so simple that it can directly be translated to a java expression.

Unfortunatly (or fortunately, depending on the point of view), simplistic let expressions like in your example, and even simple case expressions like

    huhu | otherwise = "Ha" ++ undefined

are eliminated early, so they end up as simple expressions. Hence, it is a bit of a challenge to write a definition that is guaranteed not to get evaluated right away, but after having tried a bit, I found that

    huhu | 1 < 2 = "hu" ++ undefined
    haha = "Ha" ++ const x x where x = "Blubb" ++ undefined

will do. However, it is best to assume that Frege will evaluate all super combinators (i.e. top level items) to WHNF, no matter if they are functions or not.

**Comment by danielkroeni** [comment]
I understand the performance argument. But in my opinion performance is much less important than consistent execution semantics. It would safe so much time if we could at some time in the future just compile Haskell code with the Frege compiler and get the same results on the different runtimes.

**Comment by Ingo60** [comment]
Okay, okay. :)
Turns out we will have to do this anyway, because of #169 and in order to avoid the class loading deadlock errors that can happen with too much strictness.

Therefore, I take the freedom to close this issue as a duplicate (which it is not by intention, but by conclusion, so to speak).

**Comment by Ingo60** [comment]
This works now as expected.
