### ISSUE TITLE
identifiers (Haskell adaption)

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege#208]
The relevant task is described in [slide6 : Variable Names](https://docs.google.com/presentation/d/1wdvP70ziDRaGZiKI3Zqb0ciLir4_axOH04APxaRtIsY/edit?usp=sharing)

The fix in he lexer should not be very complicated on its own.
However, underscores are used to generate names that are guaranteed not to conflict with variable names. and by this change, hat guarantee is nulled. In addition, the underscore is used in name mangling (i.e. operators, java reserved words, etc.) and there it must also not map to something equal to a user supplied name.

The introduction of new unique names happens in desugaring phases (frege.compiler.passes.Fix, frege.compiler.common.Desugar, ...) where we don't know yet which variables will exist.

When selecting a new "forbidden char" we should use something that is very, very unlikely to be used by the user (i.e. no greek, no cyrillic, no latin letters with accents, etc.). At the same time, it should be a character in the UTF-16 range, lest the lexer code gets more complex (and slow) than needed.

A good candiate would be `ʎ` which is U+028E LATIN SMALL LETTER TURNED Y, though one can see it also as a mirrored lambda.

**Comment by danielkroeni** [comment]
Why not just use the $? It seems to be the perfect fit:
> "The $ sign should be used only in mechanically generated source code or, rarely, to access pre-existing names on legacy systems." [JLS 8](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.8)

Since `$` is not allowed in Haskell we have no special forbidden char.

Yesterday night (and tonight again) I got my feet wet and to be honest, I am lost. This is what I came up with: https://github.com/danielkroeni/frege/commit/e5cbe40b18e53a8342cfe0387289cf71ef5cc9bd
At least it compiles ;) and works with my little test files.

```
cortex:frege dk$ java -cp build  frege.compiler.Main -d  test  tests/hcm/LexicalUnderscore.fr
calling: javac -cp build:test -d test -sourcepath . -encoding UTF-8 test/tests/hcm/LexicalUnderscore.java 
runtime 2.819 wallclock seconds.
cortex:frege dk$ java -cp build  frege.compiler.Main -d  test  tests/hcm/LexicalUnderscoreImport.fr
calling: javac -cp build:test -d test -sourcepath . -encoding UTF-8 test/tests/hcm/LexicalUnderscoreImport.java 
runtime 2.636 wallclock seconds.
cortex:frege dk$ java -cp build:test tests.hcm.LexicalUnderscore
main works as expected
runtime 0.004 wallclock seconds.
cortex:frege dk$ java -cp build:test tests.hcm.LexicalUnderscoreImport
final
_final
true successidentifiers and type variable may start with underscores
®
runtime 0.014 wallclock seconds.
```

I have a second commit which 'fixes' `Match.fr`:
`conGetter (MName tname base) = "_" ++ mangled base`
https://github.com/danielkroeni/frege/commit/858b42c4283b2dca8ebd00e8b1dd6a6647e103e5

There are other places which look suspicious:
`GenJava7.fr` `cMethod n = atomMethod "_constructor" (Nativ "int" []) (show n)`
Could this potentially conflict with a frege identifier? I found its definition in `Value.java` but then I was unable to locate the origin of all those `TTupleX` classes. They seem to be generated.

By the way I have no problem to replace the `"$"` with your proposed char.
If anything of this is useful I can do a PR.

**Comment by Ingo60** [comment]
Hi @danielkroeni 

the '$' is entirely ok. Apparently, I misunterstood the statement rgd. the single `_` and confused it with the `$` in general. The citation of yours convinced me.

What you've done looks good to me! I've only few remarks:

  * Dont include the `chaperlex.tex` file in the PR, as I am working on the doc in another branch anyway, so this would only give unnessecary merge conflicts.
  * Also, don't care about `Match.fr` and `GenCode7.fr` -- they'll be obsolete anyway hopefuly by end of the year.
  * The `ident` function in `lex` should be modified so as to accept any number of apostrophes. This way we catch two flies with one flap. For this, it is only necessary to check for both `_` and `'` in the first equation and returning `end` in the `otherwise` case. The helper function `skipApos` can then be deleted. Please make sure in the test code that something like `x'v'` is not interpreted as *x' applied to v'*
  * I appreciate your effort for better consistency and maintainablility through introduction of the constant `javaManglePrefix`. However, I've seen that this leads to additional imports of "Compiler.common.Mangle" in several places. This, in turn, has an influence on the degree the compiler modules can be compiled in parallel. I find this a bit expensive just for a constant. Therefore, I ask you very kindly to just use '$'. It has the additional benefit that one can see immediately what is going on. If, otoh, you want to abstract out the idea of *making a unique variable name that cannot clash with a user provided one* into a function, I'm ok with that.

I'm looking forward to your PR!

**Comment by danielkroeni** [comment]
Hi Ingo

> * Also, don't care about Match.fr and GenCode7.fr -- they'll be obsolete anyway hopefuly by end of the year.

I had to mangle the name of the `main` function. Otherwise the compiler can't find.

> * The ident function in lex should be modified so as to accept any number of apostrophes within the name, not only at the end. This way we catch two flies with one flap. For this, it is only necessary to check for both _ and ' in the first equation and returning end in the otherwise case. The helper function skipApos can then be deleted. Please make sure in the test code that something like x'v' is not interpreted as x' applied to v'

I just tried the fix you proposed and realized that situation is much more complicated than expected. With that fix every character literal will be parsed as  an identifier.
I tried to solve it by adding a case like `ch == '\'' && at (start+2) == '\''` just above the ident case to distinguish character literals from identifiers. But we also have escaped literals like '\n'. Okay that's easy to catch as well. Then I remembered the literal '\BEL' ...
```
Prelude> '\BEL'
'\a'
```
Anyway I think you have to distinguish character literals from identifiers depending on the context in the parser.

> * I appreciate your effort for better consistency and maintainablility through introduction of the constant javaManglePrefix. However, I've seen that this leads to additional imports of "Compiler.common.Mangle" in several places. This, in turn, has an influence on the degree the compiler modules can be compiled in parallel. I find this a bit expensive just for a constant. Therefore, I ask you very kindly to just use '$'. It has the additional benefit that one can see immediately what is going on. If, otoh, you want to abstract out the idea of making a unique variable name that cannot clash with a user provided one into a function, I'm ok with that.

I added the following function to `Mangle.fr`:
```haskell
-- Generates an ident which is guaranteed not to clash with any user defined ident.
noClashIdent :: String -> String
noClashIdent i = "$" ++ i
```
I decided against using `$` directly because of my experience of searching for `_` in the code base. Searching for `$` yields 5834 results. It's much easier to search for `noClashIdent`.
But `Desugar.fr`, `Fix.fr` and `Classes.fr` got a new dependency on `Mangle.fr`. Tell me if that is acceptable.

> I'm looking forward to your PR!

https://github.com/Frege/frege/pull/209

**Comment by Ingo60** [comment]
> With that fix every character literal will be parsed as an identifier.

How so? When we are in `ident`, then we have already detected a leading uppercase letter, lowercase letter or `_` (in the big switch in `lex`). That is, when we have

    x'y'

we already have the `x` and `ident` is just called to skip all characters that can be in an identifier and return the offset of the first character that can not be in an identifier.

**Comment by danielkroeni** [comment]
Ohh, I wrongly thought that a prime can be at the start of an identifier as
well. Crazy me. I fix it now.

**Comment by danielkroeni** [comment]
The fix is ready: https://github.com/Frege/frege/commit/996328becff14e1abb65eddf3bfc62d2b4da3a45

**Comment by Ingo60** [comment]
PR merged.
