### ISSUE TITLE
Build error with byacc

### ISSUE THREAD

**Issue by catull** [Frege/frege#213]
I have been seeing this a few times.

With no modified files in the workspace, the generation of frege/compiler/grammar/Frege.fr bails out with:

We should have 5 shift/reduce conflicts in the grammar.
`which byacc || which byaccj || which pbyacc || false` -v frege/compiler/grammar/Frege.y
/usr/local/bin/byacc: e - line 1200 of "frege/compiler/grammar/Frege.y", syntax error
            [fd@FunDcl {expr=x}] -> YYM.return [fd.{expr = nx}] where
               ^
Makefile:207: recipe for target 'frege/compiler/grammar/Frege.fr' failed
gmake: *** [frege/compiler/grammar/Frege.fr] Error 1

I am forced to comment out 206 - 209 to proceed.

**Comment by Ingo60** [comment]
Hmmm, this is mysterious.
I've **never** seen this before.

Also, we have travis-CI, which does a full build from zero on every push and no build has ever failed because of this.
Can it be your environment, i.e. the byacc version?

    ingo@freguntu:~/Frege/frege$ byacc -V
    byacc - 1.9 20140715

Anyway, here is a workaround:

We have the generated Frege.fr under git control just for the people out there who have no byacc or don't care to install one. Hence it should be possible to just 

    touch frege/compiler/grammar/Frege.y

and restart the make.

**Comment by catull** [comment]
At the time of the error reported, MacOS X 10.11.1, byacc -V gives
     byacc - 1.9 20141006

You probably meant to touch touch frege/compiler/grammar/Frege.fr.
Because Frege.y is the source, and Frege.fr is the output of byacc.

Anyway, the touch trick does not help.

Will try with an upgraded byacc now.

**Comment by catull** [comment]
UPDATE1:
Same error with byacc - 1.9 20150711.
byacc was built with gcc 5.2.0 and all the checks for byacc passed.

UPDATE 2:
byacc built with clang is fine, frege/compiler/grammar/Frege.fr is built without a problem.
This is not an issue anymore.
