### ISSUE TITLE
Library: Data.Array

### ISSUE THREAD

**Issue by seancorfield** [Frege/frege#221]
One of a series of placeholder issues based on Ingo's presentation about Haskell/Frege differences.

**Comment by LGLO** [comment]
Link to the presentation:
https://docs.google.com/presentation/d/1wdvP70ziDRaGZiKI3Zqb0ciLir4_axOH04APxaRtIsY/edit?usp=sharing

I've started to adapt code from GHC/Arr.hs from Haskell, I think about 80% of work for boxed arrays is done.
For sure IArray module is missing, it should mainly call code from Arr.fr.
I think I can handle this but then problem is that I know Haskell too little, I don't have any idea how proceed with unboxed arrays. I hope I'll be eventually ready to finish this topic but not soon.

**Comment by Ingo60** [comment]
This Issue is **only**  tracking compliance with Haskell 2010 (where Data.Array is specified, see the Part 2 of the Haskell 2010 report), not yet about extra features offered in  GHC libraries.
I guess you have already implemented all that is required by the Standard, just check if this is so. (Except for the (!) vs. (!!) issue, but we can't change this at the moment.)

**Comment by LGLO** [comment]
Done:
* construction: `array`, `listArray`, `accumArray`.
* updates: `(//)`,  `accum`
* access: `(!)` as `(!!)`, `indices`, `elems`, `assocs`, `bounds`
* instances: `Functor`, `Eq`, `Ord`

Missing:
* instance `Read` is missing as typeclass `Read` is
* instance `Show` is simplified, it doesn't use `showsPrec` which is missing itself.

`array` works as in GHC, not as in Report - last association wins instead of bottom - action?

Major flaw but easy to fix: `package Data.Arr` instead of `package Data.Array` or perhaps `module Data.Array` - I don't know which one is preferred after taking direction 'Haskell on the JVM'. Also file name 'Arr.fr' should become 'Array.fr'.

So, I'll do renaming. Then I'll take a look at Show instance.
Should missing 'Show' typeclass become a tracked issue?

**Comment by Ingo60** [comment]
Yes, I think so.
Also the Read type class.

Would be great if you are interested in working on that one.

**Comment by LGLO** [comment]
I was quite tired. To clarify:
* `Show` typeclass is present
* `Read` is the missing one
* I'll finish `Array`
* I'll make an issue for `Read` and if no one else takes it until I finish `Array` I'll take it.

**Comment by mabre** [comment]
The implementation of ``listArray``  in Frege does not currently work when the list has more elements than the range:
```
frege> listArray (0, 1) [0..2]
frege.runtime.Undefined: List length does not match range size
```
It works in GHC,
```
Prelude Data.Array> listArray (0, 1) [0..2]   
array (0,1) [(0,0),(1,1)]
```
which matches the definiton from the Haskell 2010 Language Report:
```
listArray :: (Ix a) => (a,a) -> [b] -> Array a b
listArray b vs = array b (zipWith (\ a b -> (a,b)) (range b) vs)
```

A consequence is that Frege gets stuck in an infinite loop when the list is infinite (e.g. ``listArray (0, 1) [0..]``).

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.
