### ISSUE TITLE
Library: System.Environment

### ISSUE THREAD

**Issue by seancorfield** [Frege/frege#227]
One of a series of placeholder issues based on Ingo's presentation about Haskell/Frege differences.

**Comment by seancorfield** [comment]
I'm happy to take a look at this one since it seems like a nice, small library. I have some questions about how best to implement some of it tho'... so I'll create separate tickets for those.

**Comment by seancorfield** [comment]
Per discussions on the mailing list:

* getArgs -- return [] for now and create a ticket (for Ingo) since "I am about to rewrite the code that generates main(), and also runMain() will change".
* getProgName -- return "" for now since this is a horrible area of compatibility and represents a very UNIX-y way of thinking about program names (we can revisit if this causes folks problems in the future: there are hacks in Java to get a "program name" from a Java class based on runtime location etc).
* getEnv -- call `java.lang.System`s `getenv` and throw an exception if that returns `Nothing` (this is a horrible API: folks should just call the Java function and deal with `Maybe` instead!).

**Comment by Ingo60** [comment]
By the way: you throw exceptions with throwST (or the slightly stronger typed throwIO, but see below).

This could make it necessary to add a constructor to some exception type of your choice. Currently, they're all just abstract types, though they can all be used in place of a Throwable, (You might look at Undefined in PreludeBase for our custom Frege exception that is thrown when someone tries to evaluate "undefined" )

A short glance at the standard lets me propose that you use the slightly more general type `ST s x` instead of `IO x`. Unlike in GHC, IO is just one incarnation of ST, but I don't see a reason why this should be restricted to "real" IO actions, as all of that stuff doesn't change anything, really.

**Comment by seancorfield** [comment]
I thought I could just add a constructor to `IllegalArgumentException` (which seemed the most logical choice here) but now I'm getting a build failure:
```
E ./frege/test/QuickCheckException.fr:84: overloaded  new  is ambiguous at type  String→Throwable
    It could mean one of 
    Undefined.newα  ::  String → Undefined
    Undefined.newβ  ::  String → Throwable → Undefined
    IllegalArgumentException.new  ::  String → IllegalArgumentException
```
I can see _why_ it thinks that's potentially ambiguous but I'm not sure how to fix it so I can do (something like) `IllegalArgumentException.new s` to get an appropriate exception with a message...?

**Comment by seancorfield** [comment]
Per discussion on Gitter, opening a new issue for this for @Ingo60 to investigate.

**Comment by seancorfield** [comment]
PR #235 sent for review to implement this.
