### ISSUE TITLE
Adding constructor to IllegalArgumentException makes Undefined.new ambiguous

### ISSUE THREAD

**Issue by seancorfield** [Frege/frege#234]
I updated `frege.java.Lang`s definition of `IllegalArgumentException` to add a constructor:

    pure native new :: String -> IllegalArgumentException

This caused a build failure in `frege.test.QuickCheckException` -- see #227 for the exact exception produced (on line 84, call to `Undefined.new`).

@Ingo60 said this was a bug that needed investigating.

**Comment by Ingo60** [comment]
The reason is a too general search for matching functions. It just collects all possible functions on the inheritance path, which is, in this case:

    Undefined -> IllegalArgumentException -> .... -> Throwable

But when we have

    T.x

it should consider **only** the the functions that overload `foo` in  `T`.  Likewise, when we have

    (v :: T).foo

Only if there is no `foo` in `T` should it consider the ones from the classes `T` extends.

This could still break existing code, however, this is then somehow better justified.

**Comment by Ingo60** [comment]
The overloading feature will now work like so:

  * It will group the candidate functions by enclosing type, and order the groups from most specific to least specific.
  * The overloading resolver filters the functions from each group that don't fit type wise.
  * If all resolved groups are empy, no matching function was found. This is a type error.
  * Otherwise, there must be a non-empty resolved group. If this group has exactly one element, this is the matching function. Otherwise, an ambiguity is reported as error.   This way, ambiguities can occur only within one and the same type.

Thus: 

    -- assume frege.runtime.Undefined extends IllegalArgumentException
    data Undefined = pure native frege.runtime.Undefined where
        pure native new :: String -> Undefined
    data IAE = pure native java.lang.IlegalArgumentException where
        pure native new :: String -> Undefined

    x = Undefined.new "example"

in the definition of `x` there is no ambiguity between

    Undefined.new
    IAE.new

as one would reasonably expect.

**Comment by mmhelloworld** [comment]
This is great! Thanks Ingo and Sean for reporting and fixing this.

I have had this issue before but I didn't bother with reporting this as I
would just explicitly annotate the type I want or some other workaround
that I don't remember now. It is great that it is fixed now but I should
have reported this issue earlier.

**Comment by seancorfield** [comment]
:+1: I look forward to this hitting master so I can clean up that `newIAE` constructor code!
