### ISSUE TITLE
Haskell things for timing that might be in Frege but are not yet

### ISSUE THREAD

**Issue by russel** [Frege/frege#236]
The standard Haskell mechanisms for timing codes seems to be:

```
import Data.Time.Clock (getCurrentTime, diffUTCTime)
```

then:

```
startTime <- getCurrentTime
...
endTime <- getCurrentTime
putStrLn ("\telapse time = " ++ show (diffUTCTime endTime startTime))
```

Sadly this doesn't work in Frege, module Data.Time.Clock is not available. In the interim:

```
startTime <- System.nanoTime ()
...
endTime <- System.nanoTime ()
putStrLn ("\telapse time = " ++ show ((fromIntegral (endTime - startTime)) / 1e9))
```

does the job.

**Comment by seancorfield** [comment]
I'm curious as to where this comes from since I don't see Data.Time(.Clock) here https://github.com/ghc/ghc/tree/c2fab84239299176a8e72aa26ae894019d677bd9/libraries/base and that seems to be the initial set of libraries Ingo wants to target for Frege (and Data.Time(.Clock) isn't part of Haskell 2010 as far as I can see from the PDF I'm reading).

If you can point me to the source of Data.Time(.Clock) I can take a look and see what it would take to create Frege wrappers around Java to implement at least some of that stuff.

**Comment by russel** [comment]
On Debian at least, I haven't checked Fedora, time-1.4.2 comes as standard in the ghc package.

**Comment by Ingo60** [comment]
It is a GHC library, but not standard.  The trouble is I have no idea
whether we should try to port this or maybe some other Hackage date/time
package? But I'm pretty sure we will have to support java.util.time sooner
or later for inter operability reasons.
In any case, this date / time stuff is a hairy affair and would need
careful consideration.

**Comment by russel** [comment]
The Haskell package didn't have GHC in front so I though it was a general Haskell package. I guess the question is where to set the Haskell/Hackage and JVM boundary for Frege. I am OK using System.nanoTime as the de facto standard Frege idiom.
