### ISSUE TITLE
Incompatible behaviour with empty list

### ISSUE THREAD

**Issue by jorander** [Frege/frege#243]
According to http://learnyouahaskell.com/starting-out , end of section "An intro to lists", `head`, `tail`, `last` and `init` should through a runtime-exception when used on empty lists. In Frege, instead of throwing exception a mysterious `a` or `[a]` is returned. This behaviour can probably lead to hard to find bugs in Frege programs.

Here are some examples from the REPL.

```haskell
frege> length []    -- OK
0

frege> null []      -- OK
true

frege> head []     -- Should have been exception
a

frege> head [] == "a"    -- Strange!
true

frege> tail []  -- Should have been exception
[a]

frege> init []  -- Should have been exception
[a]

frege> last []  -- Should have been exception
a

frege> [] ++ [] -- Strange!
[a]

frege> reverse [] -- Strange!
[a]

frege> take 1 [] -- Strange!
[a]

frege> minimum [] -- Strange!
Ord a => a

frege> sum [] -- Strange!
Num a => a
```

Tested in Frege REPL: frege-repl-1.4-SNAPSHOT

**Comment by mmhelloworld** [comment]
These are all REPL behaviors and nothing to do with Frege itself. When REPL evaluates an expression, it tries to `show` that expression. If there is no `Show` instance, then it would just print the type. All `a`s that you are seeing in the output are just type variables; they are not the actual output. It couldn't find a `Show` instance because it wouldn't know which concrete `Show` instance to it should instantiate as there is no concrete type.

If we give a concrete type, we would get the expected output:

```
frege> head [] :: [Int]
frege.runtime.Undefined: head []
```
This is the case for all the expressions in your post except for one `head [] == "a"`. This is strange and when I tried it I got the correct output:

```
frege> head [] == "a"
frege.runtime.Undefined: head []
```

Could you please try it again and confirm whether you really get `true` or an error like above for `head [] == "a"`?

Incidentally, we also just decided yesterday that we should also do something like GHCi's defaulting for these cases when the type is not known/generic but we could show the result if we default it to some type. For example (as per Ingo's suggestion on Gitter),

```
frege> []
[a]
A possible instance of this would be [()], and the output for that would be
[]
```

**Comment by jorander** [comment]
I see. Thanks for the feedback.

As for the strange case with `head [] == "a"` I went through my history and realised it was a typo that put my REPL into a strange state. Here's how to re-create. Being new to both Haskell and Frege I didn't realise the meaning of those warnings.

```haskell
Welcome to Frege 3.23.370-g898bc8c (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM, 1.8.0_45)

frege> head []
a

frege> head [] = "a"       -- Typo that set the REPL into a strage state.
function head :: [a] -> String
W <console>.fr:2: hiding previously (line 1) imported alias for class
    member function `ListView.head` through value `head`
W <console>.fr:2: function pattern is refutable, consider adding a case
    for _:_

frege> head [] == "a"
true

frege> head []
a
```
When run in  a fresh REPL I get the expected results as per your previous comment.
```haskell
Welcome to Frege 3.23.370-g898bc8c (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM, 1.8.0_45)

frege> head []
a

frege> head [] == "a"
frege.runtime.Undefined: head []
```
I think we can close this issue now.

**Comment by Ingo60** [comment]
The "strange state" was the result of you inadvertently redefining "head" by saying

    head [] = "a"

This tells the compiler that you want to define a function called "head" which is "a" when the argument is the empty list. 

The compiler/repl warns you against two things here:

1. There is already a function with that name, which is shadowed now. 

2. Your definition doesn't cover all cases. Specifically it doesn't handle non empty lists. Which would result in a runtime error should you ever pass a non empty list.
