### ISSUE TITLE
warnings building compiler e.g. appliction of <X> will diverge.

### ISSUE THREAD

**Issue by raould** [Frege/frege#254]
It would be nice if somehow perhaps the out-of-the-box compilation had no warnings as well as no errors. 
- Cloned today.
- Mac OS X 10.10.
- I think Java 1.8.0_51.

```
make runtime compiler
Making runtime
javac -encoding UTF-8 -d build -source 1.7 -target 1.7 frege/runtime/*.java frege/run/*.java
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
Runtime is complete.

Making compiler
...

$ grep -A 1 "^W" /tmp/c | pbcopy
W shadow/frege/prelude/PreludeBase.fr:950: application of throw will
    diverge.
--
W shadow/frege/prelude/PreludeBase.fr:946: application of error will
    diverge.
--
W shadow/frege/prelude/PreludeList.fr:387: foldl: It is strongly advised
    to use 'fold' instead - beware of stack overflow!
--
W ./frege/Prelude.fr:129: ST.performUnsafe: You are breaking the rules.
    Expect an arbitrary result and program crashes.
--
W ./frege/Prelude.fr:131: ST.performUnsafe: You are breaking the rules.
    Expect an arbitrary result and program crashes.
--
W ./frege/compiler/Main.fr:114: ST.performUnsafe: You are breaking the
    rules. Expect an arbitrary result and program crashes.
--
W ./frege/prelude/PreludeBase.fr:950: application of throw will diverge.
W ./frege/prelude/PreludeBase.fr:946: application of error will diverge.
calling: internal -nowarn -source 1.7 -target 1.7 -cp build:build -d build -sourcepath . -encoding UTF-8 build/bfrege/prelude/PreludeBase.java 
--
W ./frege/prelude/PreludeList.fr:387: foldl: It is strongly advised to
    use 'fold' instead - beware of stack overflow!
--
W ./frege/Prelude.fr:129: ST.performUnsafe: You are breaking the rules.
    Expect an arbitrary result and program crashes.
--
W ./frege/Prelude.fr:131: ST.performUnsafe: You are breaking the rules.
    Expect an arbitrary result and program crashes.
--
W ./frege/compiler/Main.fr:114: ST.performUnsafe: You are breaking the
    rules. Expect an arbitrary result and program crashes.
--
W ./frege/prelude/PreludeBase.fr:950: application of throw will diverge.
W ./frege/prelude/PreludeBase.fr:946: application of error will diverge.
calling: internal -nowarn -source 1.7 -target 1.7 -cp build:build -d build -sourcepath . -encoding UTF-8 build/frege/prelude/PreludeBase.java 
--
W ./frege/prelude/PreludeList.fr:387: foldl: It is strongly advised to
    use 'fold' instead - beware of stack overflow!
--
W ./frege/Prelude.fr:129: ST.performUnsafe: You are breaking the rules.
    Expect an arbitrary result and program crashes.
--
W ./frege/Prelude.fr:131: ST.performUnsafe: You are breaking the rules.
    Expect an arbitrary result and program crashes.
--
W ./frege/data/Char.fr:85: hiding previously (line 4) imported alias for
    class member function `Num.isNumber` through value `isNumber`
```

**Comment by Dierk** [comment]
well, this is kind of tricky as for example the definition of foldl uses of course foldl and thus
you get a warning for that :-)

You can even see the very existence of the warning as a "passing test". 
The absence of the warning would be an error.

cheers
Dierk

**Comment by raould** [comment]
I don't know what other FPs do but as a day-job developer I don't see this as a good state to be in long term. It is too much in the Realm of False Positives to my linking. ¥2/$0.02/etc. There should perhaps be a way to discharge the warning with a pragma at the line that would otherwise generate the warning. Or the warnings should be categorized and the compiler should support flags to squelch individual types of warning. Or some such.

**Comment by Dierk** [comment]
It is certainly a best practice to avoid false positives.

What other languages do in such a case is to have some "suppressWarnings" annotation.

**Comment by Ingo60** [comment]
I agree with regard to the "hiding previously imported symbol ...." warning from Data.Char and the warnings for the runtime.

I am of the opinion, though, that the warnings for `performUnsafe` and `foldl` are justified, if only from a maintenance perspective. But the latter one also for adapteded Haskell code: the stack in the JVM is actually so tiny compared to the Haskell RTS stack, that `foldl` over lists with a few thousand elements only will inevitably lead to stack overflows. So, while you can often get away with `foldl` in Haskell, this will not be so in Frege.

Regarding the "will diverge" warning: there are no false positives. The warning is issued in cases when the result type of some function is some type variable that doesn't appear anywhere else in the function type. This is only possible when the reult is ⊥
The warning can be suppressed by giving atype signature, i.e.

    runforever :: Int -> Int   -- a promise that will not be fulfilled ....
    runforever x = runforever x

**Comment by raould** [comment]
I still wondering: What is the point of a warning that you will never do anything about? All it does is make things noisy and confusing and needlessly alarming.

**Comment by Ingo60** [comment]
We need to define `foldl`, because it's in the Haskell 2010 standard. Only when you use `foldl`, you'll get the warning, Unfortunately, the definition of `foldl` itself uses `foldl`, so there is this warning. What do you suggest? Not define it? Define it differently from Haskell, that is, with different semantics? Or remove the warning alltogether and wait until some Haskell user complains about not getting a warning when it is well-knonw that `foldl` is almost unusable on the JVM? Or something else?

The warning regarding non-termination is valuable, I think. It is one of the rare cases where static analysis can actually tell non-terminating from terminating programs, which is wonderful. The more so as this is merely a by-product of type checking. 
The warning is issued when a function is defined that will not terminate when applied (no matter if it is actually applied in that module). Hence users using `error` will *not* get the warning. Only if hey, most probably inadvertly, define such a function themselves.
Again, we have to define `error` somehow. But when we do this, the compiler detects that it won't terminate and will issue the warning. What do you suggest that we should do about it? Remove a valuable feature just so that he who compiles the compiler is not disturbed by a warning?

We have 3 instances of `performUnsafeIO`  in the compiler and Prelude. Two of them in frege.Prelude are totally justified since they are used in the definition of `trace` and `traceLn` , which are simple but efficient debugging tools. The 3rd one in the compiler itself will eventually be removed sooner or later.
Again, the warning occurs only when one compiles Prelude.fr, *not* when one uses `traceLn`. Suggestions?

Under the assumption that he who compiles the compiler understands enough to see why those warnings are practicaly unavoidable, I realy see no importance in doing something about it.

**Comment by raould** [comment]
I suggested previously one thought, that warnings in specific lines of code be silenceable using a "#pragma silence-warning-425" or some such. That ability would be relevant to more than the compiler. It is relevant to any code that is "done" and yet uses code that is emitting warnings that are now false positives. Of course all that can go wrong later when somehow the false positive is no longer false, but by that point everybody is ignoring it anyway so it wouldn't have saved anyone.

**Comment by Ingo60** [comment]
Yes, that sounds reasonable.
