### ISSUE TITLE
unexpected token "where" when indentation of do-block same as where

### ISSUE THREAD

**Issue by mabre** [Frege/frege#272]
The following code, which compiles with ghc, only compiles with frege when removing a space before ``where``

```haskell
module DoWhere where

main = do
    print x
    where x = 1
```

```
E DoWhere.hs:5: unexpected token "where" while trying to
    parse do expression qualifiers
E DoWhere.hs:3: last statement in a monadic do block must
    not be let decls
E DoWhere.hs:5: syntax error on '}'
```

**Comment by Ingo60** [comment]
This seems to employ the following provision in the Haskell report:

> A close brace is also inserted whenever the syntactic category containing the layout list ends; that is, if an illegal lexeme is encountered at a point where a close brace would be legal, a close brace is inserted.

This is impossible in Frege, as the layout is done in the lexical analyser.

**Comment by Dierk** [comment]
How about dealing with this special case by just adding a closing brace before _any_ "where"?

**Comment by Ingo60** [comment]
Like in

    module Main } where

Dierk???

**Comment by Dierk** [comment]
well, just a _bit_ more intelligently ;-)

**Comment by Ingo60** [comment]
We can, at a later date, explore additional possibilities.
Theoretically, we could have several rules of the form: Instead of issuing a syntax error, insert X in a place where X would be allowed.

Commas, Braces, Parentheses, Brackets, Semicolons, keywords, whatever you want.
It's only making everything more complicated, including resolution of genuine syntax errors. ("Why does it complain about }}}foo when I don't have braces in that line?")

**Comment by Dierk** [comment]
true.

From a pure user standpoint, I would certainly like to have "where" inside "do" blocks - and at the moment I would trade the quality of error messages for that feature. (just my two cents)

**Comment by Ingo60** [comment]
A *where* block can follow any case alternative or RHS of a function or pattern binding. You can, of course, have case expressions and bindings inside a `do` .
