### ISSUE TITLE
type error when defining instance for function with forall

### ISSUE THREAD

**Issue by mabre** [Frege/frege#273]
Compiling the following code fails with a type error:
```haskell
module TypeErrorBug where

class Data a where
  gfoldl :: (forall d b. Data d => c (d -> b) -> d -> c b)
         -> (forall g. g -> c g)
         -> a
         -> c a

instance Data a => Data [a] where
    gfoldl f z []     = z []
    gfoldl f z (y:ys) = (z (:) `f` y) `f` ys
```

```
E TypeListBug.hs:11: type error in expression :
    type is apparently [t7590#α]
    used as function
E TypeListBug.hs:11: type error in expression z :
    type is : β [α]
    expected: β (t2→t1)
E TypeListBug.hs:11: t7605 occurs in type t7590#α→t7605 rendering
    expression f{7584} (z{7585} [].:) y{7586} untypable.
E TypeListBug.hs:11: type error in expression f (z :) y
    type is : β t1
    expected: β (α→t1)
E TypeListBug.hs:11: type `[t7590#α]` is not as polymorphic
    as suggested in the annotation where just `α` is
    announced.
E TypeListBug.hs:11: type error in expression ys
    type is : [α]
    expected: α
```
It compiles without error when commenting out one case for ``gfoldl`` (resulting in a warning ``function pattern is refutable, consider adding a case for []`` or ``_:_``, respectively).

However, defining the instance using ``case`` works:
```haskell
instance Data a => Data [a] where
     gfoldl f z x = case x of
                      (y:ys) -> (z (:) `f` y) `f` ys
                      []     -> z []
```

**Comment by Ingo60** [comment]
I think we can leave the classes and instances aside, the error would occur for standalone `gfoldl`as well (when substituting some `* -> *` type for `c` in the type signature).

## Reason

Desugaring of multi-equation functions collects the patterns of each equation in tuples, for instance in our case:

    gfoldl a1 a2 a3 = case (a1,a2,a3) of
            (f,z,[])     -> -- RHS 1
           (f,z, y:ys) -> -- RHS 2

The tuples are never actually created at runtime, but get optimized away, but unfortunately  only after typechecking. And here it is that the arguments loose their "higher-rankedness" because the tuple typechecking forces instantiation. This is why the error messages insist that `z` applied to some argument must yield a list.

## Solution

Optimize pattern matches before typechecking.
