### ISSUE TITLE
non-indented documentation comment is syntax error

### ISSUE THREAD

**Issue by mabre** [Frege/frege#274]
While porting a program to frege I came across code which looked like this:

``` haskell
module Comments where

main = f
    where
---------------------------
-- Very important function
---------------------------
        f = putStrLn "hi"
```

The “documentation” comments in lines 5 and 7 cause a syntax error:

```
E Comments.hs:4: expected '{', found ';'
E Comments.hs:4: unexpected ';' while trying to parse
    a where clause
E Comments.hs:8: syntax error on end of file
```

When the comments are indented, this error shows up instead:

```
E Comments.hs:5: unexpected documentation comment while
    trying to parse a where clause
```

I would expect that comments cannot cause syntax errors.

**Comment by Ingo60** [comment]
Right, the word *comment* probably evokes wrong expectations here.

The point is, that doc comments are comments from a lexical point of view only. But while ordinary comments have no representation in the grammer and are thrown away just like whitespace, documentation comments are syntactical elements. Therefore, they are also subject to layout processing.

And since the purpose of doc comments is to provide machine readable documentation for the public items in your module, they are not allowed on let bound functions.

Here is more explanation: https://ingo60.gitbooks.io/frege-quick-reference/content/lexical.html#_comments

**Comment by Ingo60** [comment]
I have updated the above mentioned document to make the difference between comment and documentation text more apparent.
Also, we will gradually phase out the wording *documentation comment* and replace it with *documentation text* (also in code).
