### ISSUE TITLE
Compiler error with Num instance

### ISSUE THREAD

**Issue by praalhans** [Frege/frege#294]
Found another "Can't adapt"-related error. The example is:

```
module bug.Example2 where

data Infinite n = Only n | Infinite
derive Eq (Infinite n)
derive Ord (Infinite n)
instance Show n => Show (Infinite n) where
  show (Only n) = show n
  show Infinite = "Inf"

instance Num n => Num (Infinite n) where
  zero = (Only zero)
  one  = (Only one)
  negate = undefined
  (Only n) + (Only m) = Only (n + m)
  _ + _ = Infinite
  a - b = subtract a b
  (Only n) * (Only m) = Only (n * m)
  _ * _ = Infinite
  subtract (Only n) (Only m) = if m > n then zero else Only (n - m)
  subtract Infinite _ = Infinite
  subtract _ Infinite = zero
  abs i = i
  fromInteger i = Only n where
    m = fromInteger i
    n = if m < zero then zero else m
  fromInt i = Only n where
    m = fromInt i
    n = if m < zero then zero else m
  isInfinite Infinite = true
  isInfinite _ = false

bug :: Infinite Int
bug = Infinite
```

And the error is:

```
frege.runtime.Undefined: Can't adapt
Bind {Num a => Infinite a->Infinite a, Func.U<TInfinite<𝓐>, TInfinite<𝓐>>, PreludeBase.<Func.U<TInfinite<𝓐>, TInfinite<𝓐>>>undefined().call()}
to  Func.U<PreludeBase.CNum<𝓐>, Func.U<TInfinite<𝓐>, TInfinite<𝓐>>>
because  TInfinite<𝓐>  does not match  PreludeBase.CNum<𝓐>
```

(snipped stack trace)

Replacing

`negate = undefined`

by 

`negate n = undefined`

resolves the error.

**Comment by matil019** [comment]
It seems the presence of constraints has the impact.

Here, `X` doesn't crash the compiler but `Y` and `Z` do:

```fr.hs
module Main4 where

class Foo a where
  foo :: a -> a  -- must be a function (nullary functions don't crash)

data X n = X

instance Foo (X n) where
  foo = undefined

nobug :: X Int
nobug = X

data Y n = Y

instance Foo n => Foo (Y n) where
  foo = undefined

bug :: Y Int   -- absence of type annotations doesn't change the outcome
bug = Y

class Unrelated a where
  bar :: a -> a

instance Unrelated n => Foo (Z n) where
  foo = undefined

bug' :: Z Int
bug' :: Z
```

**Comment by matil019** [comment]
Simplified further. This gives the same error:

```hs
class Foo a

bug :: Foo a => a -> a
bug = undefined
```

**Comment by Ingo60** [comment]
Now this is something one can work with!

**Comment by Ingo60** [comment]
Yeah, there is an error in eta-expansion.

I could still reduce @matil019 example to

    schlecht :: Eq a => a -> a
    schlecht  = undefined 

(we don't need that class, it has nothing to do with type classes )
Interestingly, the equivalent (manually eta-expanded)

    schlecht :: Eq a => a -> a
    schlecht x = undefined x

*does* compile fine. Why is this? Because in both cases the type checker assigns the Rho type

    Eq a => a -> a

to the RHS. Hence in the error case we have after typechecking:

    undefined :: Eq a => a -> a

whereas in the correct case we have:

      undefined :: a -> a
      undefined x :: Eq a => a -> a

Now, for function applications, the constraint (Eq a)  is simply ignored. The code generation is only interested in constraints when they appear on *named functions* because that is supposed to mean  we   have a java signature like

    public <A> undefined(CEq<A>, ....)

and now it tries to establish that at all costs. Since a generic type variable can only stand for a first class frege type (and not for an instance), this fails.

Now, the error is that during eta-expansion, it tranforms

     undefined :: Eq a => a -> a

to 

    ((undefined :: Eq a => a -> a)  (eta1234 :: a)) :: a

but it should be:

        ((undefined :: a -> a)  (eta1234 :: a)) :: Eq a =>  a
