### ISSUE TITLE
Frege on the dotNET

### ISSUE THREAD

**Issue by abhi18av** [Frege/frege#325]
Hello @Ingo60 

Since the last time I was experimenting with `frege` I've absolutely come to enjoy using the language - thanks for sharing this awesome work!

The thing is I'd like to port it to the new `dotNET-core` being worked on by Microsoft in the open, but unfortunately I don't see the `original java source` for this purpose. Or perhaps there's a work-around to that which enables me to have Frege(Haskell) on the dotNET as well?

Oh, and would that be disrespectful towards your copyright ? - Please do let me know.

**Comment by Ingo60** [comment]
Dear @abhi18av , thank you for your kind words.

Porting the whole system to dot-net seems almost impossible.
This is so because 

-  compiler uses features of the JVM that will work differently in dot-net, as far as I know. For example, reflection and annotations.

- compiler produces Java code. One would have to make it produce C# or MSIL right away.

- the Prelude and other libraries references JVM classes and methods through native methods. One would have to make a dotnet-Version of all code that has native references.

OTOH there are things like  [IKVM](http://www.ikvm.net/uses.html)
I haven't tried this but it should at least be possible to run a compiled Frege program on dotnet.
Maybe you can play around with this a bit so that we get some knowledge or even some recipes, how-to, etc.

Concerning the java sources, there are none, except a handful of runtime classes. However, since the Frege compiler leaves behind intermediary Java source code, you can get it simply by compiling the compiler (see the Wiki for that).

Our copyright is BSD, this means you can do whatever you want with the code, as long as you don't misrepresent its origin.

**Comment by abhi18av** [comment]
Ah, that's a relief - thanks :smile: 

Actually, I dabble a lot with `F#` on the `dotNET core` which is about to get an upgrade as per the `.net standard 2.0` so most of the mature libs are being ported from the `mono` and `.net framework - windows`.  We might be able to get this working over there using, as you mentioned IKVM, I've seen this in use before.

The famous Stanford-NLP has already been compiled successfully for the `.net` as mentioned in [this blog post](https://sergeytihon.wordpress.com/2013/10/26/stanford-corenlp-is-available-on-nuget-for-fc-devs/) - dated 2013.

So, I'm exited to have a great pet project :)

**Comment by Ingo60** [comment]
A pet as big as a Great Swiss Mountain Dog. :)

Wish you good luck with this, and please keep in contact.

**Comment by abhi18av** [comment]
Yes, definitely! :)
