### ISSUE TITLE
Compiler warns a pattern is not exhaustive when it actually is

### ISSUE THREAD

**Issue by matil019** [Frege/frege#333]
The compiler warns that a pattern is not exhaustive when it actually is, if a function has more than one argument, and one of the arguments is a record and another is a list.

An example I've found:

```frege
module A where

data Test = Test { x :: Int }

foo :: Test -> [Int] -> IO ()
foo _ [] = return ()
foo (t@Test{}) (y:ys) = foo t ys
```

An error message:

```
W /path/to/A.fr:7: pattern match is not exhaustive, consider adding a case for  []
```

Bisecting indicates that this is introduced by 0643a6b5f74ac11e578f8127a0be18c0fd9fa93d.

### Workaround

Mention the record pattern in all of the cases even if not needed.

```frege
-- ...
foo (_@Test{}) [] = return ()
foo (t@Test{}) (y:ys) = foo t ys
```

**Comment by Ingo60** [comment]
I guess it doesn't "see" that the constructor is actually irrefutable, though of course it should.

By the way, excellently documented issues!

**Comment by Ingo60** [comment]
We will solve such cases by changing the order the patterns are compiled in such a way that the patterns belonging to an argument are preferred when they are either all constructors, all variables or all literals.

In the given case, we'd compile the list patterns first. Since they are complete, there will be no complaints about missing list constructors. And each of the sub-cases will then have an irrefutable pattern.

As far as I can see, this works in the general case as well. (The vertical order of the attempts will not change, and it shouldn't matter in what order we match the patterns of an equation - there is either an overall match or not)

**Comment by Ingo60** [comment]
In the first step, overlapping patterns with product constructors are handled like this: the overlap could only be caused by variables. So we replace:

    foo v [] = [v]
    foo (y@Test{}) (_:xs) = foo y xs

which is desugared as 

    foo = case (arg1, arg2) of
        (v, []) -> [v]
        (y@Test{}, (_:xs)) -> foo y xs

with

    foo = case arg1 of 
        Test{} -> case arg2 of
           [] -> [arg1]
          (_:xs) -> case arg1 of { y -> foo y xs }
