### ISSUE TITLE
Support updating multiple record fields whose types change

### ISSUE THREAD

**Issue by matil019** [Frege/frege#343]
Suppose we have a record type with a type parameter:

```example.fr.hs
data NamedPair a = NamedPair { name :: String, x :: a, y :: a }
```

Obviously, changing only one of `x` or `y` doesn't type check, because their type must be the same:

```change1.fr.hs
let p = NamedPair { name = "hello", x = 1, y = 2 }  -- NamedPair Int
in p.{ x = "foo" }                                  -- Compilation error (NamedPair ?)
```

However, changing both of them at once doesn't pass the compilation either:

```change2.fr.hs
let p = NamedPair { name = "hello", x = 1, y = 2 }  -- NamedPair Int
in p.{ x = "foo", y = "bar" }                       -- Compilation error (intended to be NamedPair String)
```

I understand that, as I believe the update syntax is desugared like the following:

```desugar.fr.hs
  p.{ x = "foo", y = "bar" }
= p.{ x = "foo"}.{ y = "bar" }
= (p.upd$x "foo").upd$y "bar"
```

However, if we change the desugaring like below, it should be possible:

```newdesugar.fr.hs
-- newdesugar
  p.{ x = "foo", y = "bar" }
= NamedPair
  { x = "foo", y = "bar"
  , name = p.name
  -- , copy other fields of p if any...
  }
```

### Workaround

Write manually like "newdesugar" above, or put the typed fields into a separate record type:

```workaround.fr.hs
data Pair a = Pair { x :: a, y :: a }
data NamedPair a = NamedPair { name :: String, p :: Pair a }

let np = NamedPair { name = "hello", p = Pair { x = 1, y = 2 } }
in np.{ p = Pair { x = "foo", y = "bar" } }
```

I have a feeling that even if the proposed update desugaring gets supported, refactoring this way makes the structure of the code better.
Nevertheless, I think it's reasonable to support this feature if Frege supports the update syntax.

Note that GHC supports the feature without enabling any extension.
The relevant part of Haskell 2010 Report: 3.15.3 Updates Using Field Labels.

**Comment by Ingo60** [comment]
Another workaround could be to define

    data Pair' a b = Pair { x::a, y::b }
    type Pair a = Pair' a a

Then it would be ok that the intermediate pair has different types for x and y.

**Comment by Ingo60** [comment]
The point is that your proposal would make things much more complex. The reason being that it is not just a desugaring. For when we see

    expr.{id1 = expr1, id2 = expr2}

we can't just desugar it before we know the type of `expr`.
Whereas currently, the desugaring is done right in the parser, and the rest is done by type directed name resolution. That is, after parsing, the code is already

     (expr.upd$id1 expr1).upd$id2 expr2

In Haskell, this is different, since `id1` and `id2` are global functions with a known type. In Frege, `upd$id1` and `upd$id2` are functions that live only in the namespace provided by some (unknown, until after typechecking) type.
