### ISSUE TITLE
Type-flipping newtype doesn't work with Functor

### ISSUE THREAD

**Issue by matil019** [Frege/frege#348]
If a `newtype` declaration has two type variables and wraps another two-type-variable type with its variables flipped, a definition of a `Functor` instance of it crashes the compiler.

This works:

```NoFlip.fr.hs
module NoFlip where

newtype NoFlip a b = NoFlip (a, b)

instance Functor (NoFlip a) where
  fmap f (NoFlip (a, b)) = NoFlip (a, (f b))
```

This does not:

```Flip.fr.hs
module Flip where

newtype Flip a b = Flip (b, a)

instance Functor (Flip a) where
  fmap f (Flip (b, a)) = Flip ((f b), a)
```

```
$ fregec Flip.fr
calling: javac -cp /home/yohashi/lib/java/fregec.jar:. -d . -sourcepath . -encoding UTF-8 ./Flip.java 
./Flip.java:104: error: type argument TTuple2<?,𝓐> is not within bounds of type-variable 𝓕
final public static class IFunctor_Flip<𝓐> implements PreludeMonad.CFunctor<PreludeBase.TTuple2<?, 𝓐>> {
                                                                                                ^
  where 𝓐,𝓕 are type-variables:
    𝓐 extends Object declared in class IFunctor_Flip
    𝓕 extends U<𝓕,?> declared in interface CFunctor
./Flip.java:104: error: IFunctor_Flip is not abstract and does not override abstract method <𝓐#1,𝓑>ƒfmap(Lazy<frege.run8.Func.U<𝓐#1,𝓑>>,Lazy<frege.run.Kind.U<TTuple2<?,𝓐#2>,𝓐#1>>) in CFunctor
final public static class IFunctor_Flip<𝓐> implements PreludeMonad.CFunctor<PreludeBase.TTuple2<?, 𝓐>> {
                    ^
  where 𝓐#1,𝓑,𝓕,𝓐#2 are type-variables:
    𝓐#1 extends Object declared in method <𝓐#1,𝓑>ƒfmap(Lazy<frege.run8.Func.U<𝓐#1,𝓑>>,Lazy<frege.run.Kind.U<𝓕,𝓐#1>>)
    𝓑 extends Object declared in method <𝓐#1,𝓑>ƒfmap(Lazy<frege.run8.Func.U<𝓐#1,𝓑>>,Lazy<frege.run.Kind.U<𝓕,𝓐#1>>)
    𝓕 extends frege.run.Kind.U<𝓕,?> declared in interface CFunctor
    𝓐#2 extends Object declared in class IFunctor_Flip
./Flip.java:110: error: name clash: <α,𝓑#1>ƒfmap(Lazy<frege.run8.Func.U<α,𝓑#1>>,Lazy<frege.run.Kind.U<TTuple2<α,?>,𝓐#1>>) in IFunctor_Flip and <𝓐#2,𝓑#2>ƒfmap(Lazy<frege.run8.Func.U<𝓐#2,𝓑#2>>,Lazy<frege.run.Kind.U<𝓕,𝓐#2>>) in CFunctor have the same erasure, yet neither overrides the other
  @Override final public <α, 𝓑> Kind.U<PreludeBase.TTuple2<𝓑, ?>, 𝓐> ƒfmap(
                                                                        ^
  where α,𝓑#1,𝓐#1,𝓐#2,𝓑#2,𝓕 are type-variables:
    α extends Object declared in method <α,𝓑#1>ƒfmap(Lazy<frege.run8.Func.U<α,𝓑#1>>,Lazy<frege.run.Kind.U<TTuple2<α,?>,𝓐#1>>)
    𝓑#1 extends Object declared in method <α,𝓑#1>ƒfmap(Lazy<frege.run8.Func.U<α,𝓑#1>>,Lazy<frege.run.Kind.U<TTuple2<α,?>,𝓐#1>>)
    𝓐#1 extends Object declared in class IFunctor_Flip
    𝓐#2 extends Object declared in method <𝓐#2,𝓑#2>ƒfmap(Lazy<frege.run8.Func.U<𝓐#2,𝓑#2>>,Lazy<frege.run.Kind.U<𝓕,𝓐#2>>)
    𝓑#2 extends Object declared in method <𝓐#2,𝓑#2>ƒfmap(Lazy<frege.run8.Func.U<𝓐#2,𝓑#2>>,Lazy<frege.run.Kind.U<𝓕,𝓐#2>>)
    𝓕 extends frege.run.Kind.U<𝓕,?> declared in interface CFunctor
./Flip.java:110: error: method does not override or implement a method from a supertype
  @Override final public <α, 𝓑> Kind.U<PreludeBase.TTuple2<𝓑, ?>, 𝓐> ƒfmap(
  ^
4 errors
E Flip.fr:6: java compiler errors are most likely caused
    by erroneous native definitions
```

Possibly the cause of #293.

---

This error looks like to be caused by the fact that `PreludeMonad.CFunctor<F>` expects `F extends U<F, ?>`, but `Prelude.TTuple2<?, A>` extends `U.<TTuple2<?, ?>, A>`.

cf. if not flipped, `Prelude.TTuple2<A, ?>` extends `U.<TTuple2<A, ?>, ?>`, so OK.

**Comment by Ingo60** [comment]
Exactly. This is something that is simply not supported. The ratioale is this: 

     newtype Pair b a = Pair (a,b)

tells us that the representation of `Pair b a` is the same as `(a,b)`  
In fact, all constructor applications and pattern matches regarding Pair are simply skipped. And because in the choosen java representation for kinds, the omitted types *must* start from the right, the whole thing fails.

Admittedly, the compiler should foresee this instead of happily producing wrong code. Maybe this is something we can achieve. But I haven't found yet a convincing method to tell "well behaving" newtypes from wrong ones.

In a sense, the Haskell programmer faces the same problem, on another level. He cannot easily make a functor that affects the first element of a tuple, so he resorts to *newtype*. The point is that Java simply does not have such a mechanism, as far as I am aware of. 

Hence, the only possibility is to use **data** instead of **newtype**.

Another possibility I haven't tried would perhaps be:

     data Pair b a = pure native frege.prelude.PreludeBase.TTuple2 {a,b}

but this, of course, has different problems (i.e., no pattern matching ...)

**Comment by yuxuanchiadm** [comment]
Related to #293
