### ISSUE TITLE
Annotation overwrites inferred constraint

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege#53]
The following code:

```
main args = println []
```

type checks without errors, but then in code generation the compiler aborts with:

```
F frege/Scrap.fr:6:  unknwon context: Show <3251 a>
```

Correct behaviour would be when the type checker would complain that the inferred type is more constrained than the annotated one. Note that there is the implicit annotation:

```
main :: [String] -> IO ()
```

**Comment by muhuk** [comment]
I am getting a similar error with the following code:

    f :: String -> IO Bool
    f s = catch (return (s == "foo")) (\_ -> return false)

Here is the error message:

    inferred type is more constrained than expected type
       inferred:  JavaType t29603 => String -> IO Bool
       expected:  String -> IO Bool

-----

`f` is just to illustrate the problem. I have this function in my actual code:

    encodeNamespaced :: Namespaced -> String
    encodeNamespaced (Namespaced _ "") = error "name part cannot be empty"
    encodeNamespaced (Namespaced "" s) = s
    encodeNamespaced (Namespaced ns s) = ns ++ "/" ++ s

This is an internal function, and the name part should never be `""`, so throwing an error there is better than using a `Maybe` return value. But I still would like to test this. I tried `expectFailure`, but then realized it tests stuff like `true == false`, and not exceptions. So that's why I was trying to `catch` and return `false`.

-----

I am currently using `frege.ide_3.23.370.a`. I will try with the newest plugin now.

**Comment by muhuk** [comment]
Aaand it doesn't work at all. Frege/eclipse-plugin#20

**Comment by Ingo60** [comment]
Catch requires that the Handler takes an Exceptional type.
Hence the constraint in the type of catch

    catch ∷ JavaType γ ⇒ ST β α → (γ→ST β α) → ST β α

(It should read `Exceptional` instead of `JavaType`, though).

You can't just annotate a constraint away. Compare:

    myshow :: a -> (Int, String)
    myshow a = (42, show a)

Correct it like so:

    f s = catch (return (s == "foo")) (\(_::Throwable) -> return false)

Nicer:

    f s = return (s == "foo") `catch`  everything
       where
           everything :: Throwable -> IO Bool
           everything _ = return false

The background is that the native code of `catch` will need something to decide if the thrown exception is the one it should handle. The JavaType type class has a method to make a `java.lang.Class` object, and this is then passed to the native code that does the exception handling.
